import React from 'react'
import type { Metadata } from 'next'

import Breadcrumb from '../../layout/shared/breadcrumb/Breadcrumb'
import Integartionpage from '@/app/components/pages/integration/Integartionpage'


export const metadata: Metadata = {
    title: 'Integration',
    description: 'Generated by create next app',
}


const BCrumb = [
    {
        to: '/',
        title: 'Home',
    },
    {

        title: 'Integration',
    },
]


function Integration() {
    return (
        <>
            <Breadcrumb title='Integration' items={BCrumb} />
            <Integartionpage />
        </>
    )
}

export default Integration