"use client";
import React, { useContext } from "react";
import { ImageContext } from "@/app/context/ImageAiContext";
import Image from "next/image";
import { Alert, Box, Grid, Skeleton, Typography, useTheme } from "@mui/material";

import BlankCard from "../../shared/BlankCard";

function GeneratedImageDisplay() {
  const { displayedImages, isGenerating, isUsingMock, } =
    useContext(ImageContext);
  const theme = useTheme();

  return (
    <BlankCard sx={{ padding: 3 }} >
      <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
        <Box>
          {isGenerating ? (
            <Typography variant="h4">Generating... </Typography>
          ) : (

            <Typography variant="h4">Results </Typography>
          )}
        </Box>

        {/* Show alert only if using mock data */}
        {isUsingMock && (

          <Alert severity="info" sx={{ bgcolor: 'primary.light', color: "primary.main" }} > These images are part of a simulated AI response for testing
            purposes. They were not generated by an actual AI system.</Alert>
        )}

        {isGenerating ? (

          <Grid container spacing={2} >

            {[...Array(isUsingMock ? 4 : 1)].map((_, idx) => (

              <Grid
                key={idx}
                size={{
                  xs: 6,
                  sm: 4,
                  md: 3,

                }}
              >
                <Box
                  sx={{
                    width: '100%',
                    aspectRatio: '1 / 1',
                    overflow: 'hidden',
                    backgroundColor: theme.palette.mode === 'dark' ? 'grey.700' : 'grey.300',

                  }}
                >
                  <Skeleton
                    variant="rectangular"
                    width="100%"
                    height="100%"
                    sx={{
                      backgroundColor: theme.palette.mode === 'dark' ? 'grey.600' : 'grey.200',
                    }}
                  />
                </Box>
              </Grid>
            ))}
          </Grid>
        ) : (
          <Grid container spacing={2}>
            {displayedImages.map((img: string, idx: number) => (
              <Grid key={idx} size={{ xs: 6, sm: 3 }}>
                <Box sx={{
                  position: 'relative',
                  width: '100%',
                  aspectRatio: '1 / 1',
                  overflow: 'hidden',
                }}>
                  <Image
                    src={img}
                    alt={`Generated ${idx}`}
                    fill
                    style={{ objectFit: 'cover' }}
                  />
                </Box>
              </Grid>
            ))}
          </Grid>
        )}
      </Box>
    </BlankCard>
  );
}

export default GeneratedImageDisplay;
