export const userData = [
  {
    id: "u1",
    avatar: "/images/profile/user-1.jpg",
    name: "James Johnson",
    role: "Admin",
    age: 30,
    phone: "123-456-7890",
    email: "alice@company.com",
  },
  {
    id: "u2",
    avatar: "/images/profile/user-9.jpg",
    name: "Maria Hernandez",
    role: "User",
    age: 45,
    phone: "555-312-8899",
    email: "bobsmith@gmail.com",
  },
  {
    id: "u3",
    avatar: "/images/profile/user-3.jpg",
    name: "Clara Mason",
    role: "Superadmin",
    age: 38,
    phone: "402-123-4567",
    email: "clara@enterprise.com",
  },
  {
    id: "u4",
    avatar: "/images/profile/user-2.jpg",
    name: "Derek White",
    role: "Moderator",
    age: 29,
    phone: "212-321-6789",
    email: "derek@forum.com",
  },
  {
    id: "u5",
    avatar: "/images/profile/user-5.jpg",
    name: "Eva Carter",
    role: "Author",
    age: 33,
    phone: "678-999-8212",
    email: "eva@blogging.com",
  },
  {
    id: "u6",
    avatar: "/images/profile/user-10.jpg",
    name: "Frank Zhou",
    role: "User",
    age: 41,
    phone: "504-222-9990",
    email: "fzhou@yahoo.com",
  },
  {
    id: "u7",
    avatar: "/images/profile/user-1.jpg",
    name: "Grace Lee",
    role: "Admin",
    age: 27,
    phone: "703-301-4444",
    email: "gracelee@company.com",
  },
  {
    id: "u8",
    avatar: "/images/profile/user-8.jpg",
    name: "Henry Ford",
    role: "Superadmin",
    age: 52,
    phone: "888-456-1234",
    email: "henry.ford@auto.com",
  },
];
